[theme]
# The primary accent color for interactive elements (buttons, borders, etc.)
primaryColor = "#e6007e"
base = "light"

# The background color for the main app area (can be white or another color)
backgroundColor = "#ffffff"

# The background color for the sidebar
secondaryBackgroundColor = "#f3f3f3"

# The color for text
textColor = "#31333F"

# The font for the app
font = "sans serif"

[server]
enableCORS = true
corsAllowedOrigins = ['https://12taste.com', 'https://streamlit.app', 'https://streamlit.io', 'https://github.com', 'https://fifi-co-pilot-v1-121263692901.europe-west4.run.app']

