[server]
# This is the single most important setting for embedding.
# It tells Streamlit to prepare for being embedded in an iframe.
headless = true

# Enable CORS and explicitly set the CSP header for maximum compatibility.
enableCORS = true
corsAllowedOrigins = ['https://www.12taste.com/', 'https://12taste.com/']
enableXsrfProtection = false # Often needed for embedded apps with forms/buttons

[browser]
# This is less critical for the embedding itself but good to have.
serverAddress = "fifi-co-pilot-v1-121263692901.europe-west4.run.app"

[theme]
primaryColor = "#e6007e"
base = "light"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f3f3f3"
textColor = "#31333F"
font = "sans serif"
showWidgetBorder = true
[theme.sidebar]
borderColor = "#e6007e"
